### ISSUE TITLE
Missing manual

### ISSUE THREAD

**Issue by gnbl** [floppes/stm32doom#1]
Works fine with Shareware file linked at http://doomwiki.org/wiki/DOOM1.WAD from FAT-formatted drive.
Navigate menus  / move with touch panel regions:
- forward: upper third
- left/right: next to weapon
- back: lower third except menu
- fire: blue user button
- jump: ?

**Comment by floppes** [comment]
Thanks for the summary!

There is no jumping as the original Doom never had it: http://doom.wikia.com/wiki/Jumping
