### ISSUE TITLE
Linker errror in Windows

### ISSUE THREAD

**Issue by MM2forever** [floppes/stm32doom#2]
Hi there,
i had to add `-specs=nosys.specs` to the LDFLAGS in the Makefile to make it work because of errors like
`signalr.c:(.text._getpid_r+0x0): undefined reference to `_getpid’ `

See here
https://www.openstm32.org/forumthread2449

I used "gcc-arm-none-eabi-9-2020-q2-update-win32"

Best wishes
Christian

**Comment by floppes** [comment]
Thanks, I haven't touched the project in a few years. Newer GCC versions require more system call functions to be implemented. Instead of your fix, I added those functions. It should compile again with GCC 9.
