### ISSUE TITLE
Linker issue

### ISSUE THREAD

**Issue by olkur** [floppes/stm32doom#3]
I faced an issue with a linker:
/Users/admin/Projects/gcc-arm-none-eabi-10-2020-q4-major/bin/../lib/gcc/arm-none-eabi/10.2.1/../../../../arm-none-eabi/bin/ld: bin/stm32doom.elf section `.bss' will not fit in region `ram'
/Users/admin/Projects/gcc-arm-none-eabi-10-2020-q4-major/bin/../lib/gcc/arm-none-eabi/10.2.1/../../../../arm-none-eabi/bin/ld: region `ram' overflowed by 63144 bytes

I did not do any changes.
Just did make inside just cloned repo.

**Comment by floppes** [comment]
I can confirm this problem with gcc-arm-none-eabi-10-2020-q4-major. Not even `-Os` helps.
It still worked with gcc-arm-none-eabi-9-2020-q2-update. They must have changed something in the compiler, probably a library grew in size. I'll have to look into this when I find some time.

**Comment by olkur** [comment]
Thanks.
Ill try to use gcc-arm-none-eabi-9-2020-q2-update.
If I find a reason why a size was grown Ill write here.

**Comment by olkur** [comment]
@floppes With compiler gcc-arm-none-eabi-9-2020-q2-update I have same issue:
```
/Users/admin/Projects/gcc-arm-none-eabi-9-2020-q2-update/bin/../lib/gcc/arm-none-eabi/9.3.1/../../../../arm-none-eabi/bin/ld: bin/stm32doom.elf section `.bss' will not fit in region `ram'
/Users/admin/Projects/gcc-arm-none-eabi-9-2020-q2-update/bin/../lib/gcc/arm-none-eabi/9.3.1/../../../../arm-none-eabi/bin/ld: region `ram' overflowed by 63144 bytes
collect2: error: ld returned 1 exit status
```

I am not sure (as I understand cross-compiler should work the same regardless of OS) but can it be because of I am using MacOS?

**Comment by floppes** [comment]
Did you re-compile everything? Just delete the `bin` directory or run `make clean`.

**Comment by olkur** [comment]
I did recompilation from scratch ( make clean ) but it didn't help.
Then I tried it again and all is working fine now so it looks that I forgot to do something update PATH or make clean.

I am going to look at why size was change a little bit.

**Comment by floppes** [comment]
I found a solution here: https://wiki.gentoo.org/wiki/Gcc_10_porting_notes/fno_common

The old Doom code doesn't use `extern` for global variables. GCC 10 therefore creates those variables multiple times in memory, resulting in a much higher memory usage.

I added the `-fcommon` compiler switch to fix it.
